epochs: 200
save_dir: saved/
save_period: 1
verbosity: 2
monitor: min val_loss
early_stop: 100
visualize: wandb
wandb_project: nv_homework
wandb_name: one_batch_test
wandb_entity: wandb_pirogok
len_epoch: 50
batch_acum: 1
log_step: 3
grad_norm_clip: 150
